dist: trusty
sudo: false
language: python

python:
  - 2.7

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - pandoc
      - pandoc-citeproc
      - r-base
      - r-base-dev

install:
  - pip install pyyaml
  - export R_LIBS_USER="$HOME/R_libs"
  - R -e 'install.packages("rmarkdown", repos = "http://cran.rstudio.com/")'

script:
  - export R_LIBS_USER="$HOME/R_libs"
  - make all pdfchapters

other:
  - texlive
