dist: trusty
sudo: false
language: python

python:
  - 2.7

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - pandoc
      - pandoc-citeproc
      - r-base
      - r-base-dev

install:
  - pip install pyyaml
  - mkdir -p ~/R_libs
  - R -e '.libPaths("~/R_libs"); .libPaths()'
  - R -e 'install.packages("rmarkdown", libs = "~/R_libs", repos = "http://cran.rstudio.com/")'

script: make all pdfchapters

other:
  - texlive
