dist: trusty
sudo: false
language: python

python:
  - 2.7

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - pandoc
      - pandoc-citeproc
      - r-base
      - r-base-dev

install:
  - pip install pyyaml
  - mkdir -p ~/R/library
  - echo "R_LIBS=~/R/library" > ~/.Renviron
  - R -e '.libPaths()'
  - R -e 'install.packages("rmarkdown", lib = "~/R/library", repos = "http://cran.rstudio.com/")'
  - R -e '.libPaths()'

script:
  - R -e '.libPaths()'
  - make all pdfchapters

other:
  - texlive
