dist: trusty
sudo: false
language: python

python:
  - 2.7

addons:
  apt:
    packages:
      - pandoc
      - pandoc-citeproc
      - r-base

install:
  - pip install pyyaml
  - mkdir $HOME/R_libs
  - export R_LIBS="$HOME/R_libs"
  - R -e 'install.packages("rmarkdown", repos = "http://cran.rstudio.com/")'

before_script:
  - export R_LIBS="$HOME/R_libs"

script: make all pdfchapters

other:
  - texlive
